FROM phpmyadmin/phpmyadmin:latest

# Update Apache to listen on custom port
RUN sed -i 's/Listen 80/Listen 8084/g' /etc/apache2/ports.conf && \
    sed -i 's/:80/:8084/g' /etc/apache2/sites-available/000-default.conf

EXPOSE 8084

CMD ["apache2-foreground"]
