openapi: 3.0.3
info:
  title: Pelanggan API
  version: 1.0.0
  description: Dokumentasi endpoint PelangganController untuk fitur pelanggan pada platform Chill Ajar.
servers:
  - url: http://localhost:8000/api
paths:
  /pelanggan/profil-saya:
    get:
      summary: Lihat profil pelanggan yang sedang login
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Mengambil data profil pelanggan yang sedang login beserta data user terkait.

        Contoh penggunaan (curl):
        ```bash
        curl -X GET \
          http://localhost/api/pelanggan/profil-saya \
          -H "Authorization: Bearer <token>"
        ```
      responses:
        "200":
          description: Data profil pelanggan
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pelanggan"
              example:
                id: 7
                user_id: 8
                user:
                  id: 8
                  nama: "Siti Aminah"
                  email: "siti@example.com"
  /pelanggan/daftar-course:
    get:
      summary: Daftar semua course
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Mengambil daftar seluruh course beserta data mentor dan user mentor.

        Contoh penggunaan (curl):
        ```bash
        curl -X GET \
          http://localhost/api/pelanggan/daftar-course \
          -H "Authorization: Bearer <token>"
        ```
      responses:
        "200":
          description: Daftar course
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"
              example:
                - id: 1
                  namaCourse: "Kalkulus Dasar"
                  deskripsi: "Materi kalkulus untuk pemula."
                  mentor_id: 2
                  mentor:
                    id: 2
                    user_id: 5
                    rating: 4.8
                    biayaPerSesi: 150000
                    gayaMengajar: "Online"
                    deskripsi: "Berpengalaman mengajar matematika SMA."
                    user:
                      id: 5
                      nama: "Budi Santoso"
                      email: "budi@example.com"
  /pelanggan/cari-mentor:
    get:
      summary: Cari mentor berdasarkan mata kuliah
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Cari mentor berdasarkan nama course.

        Contoh penggunaan (curl):
        ```bash
        curl -X GET \
          "http://localhost/api/pelanggan/cari-mentor?namaCourse=Kalkulus%20Dasar" \
          -H "Authorization: Bearer <token>"
        ```
      parameters:
        - in: query
          name: namaCourse
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Daftar mentor
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mentor"
              example:
                - id: 2
                  user_id: 5
                  rating: 4.8
                  biayaPerSesi: 150000
                  gayaMengajar: "Online"
                  deskripsi: "Berpengalaman mengajar matematika SMA."
                  user:
                    id: 5
                    nama: "Budi Santoso"
                    email: "budi@example.com"
  /pelanggan/detail-mentor/{mentorId}:
    get:
      summary: Lihat detail mentor
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Lihat detail mentor berdasarkan ID.

        Contoh penggunaan (curl):
        ```bash
        curl -X GET \
          http://localhost/api/pelanggan/detail-mentor/2 \
          -H "Authorization: Bearer <token>"
        ```
      parameters:
        - in: path
          name: mentorId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Detail mentor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mentor"
              example:
                id: 2
                user_id: 5
                rating: 4.8
                biayaPerSesi: 150000
                gayaMengajar: "Online"
                deskripsi: "Berpengalaman mengajar matematika SMA."
                user:
                  id: 5
                  nama: "Budi Santoso"
                  email: "budi@example.com"
  /pelanggan/pesan-sesi:
    post:
      summary: Pesan sesi pengajaran
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Pesan sesi pengajaran dengan mentor tertentu.

        Contoh penggunaan (curl):
        ```bash
        curl -X POST \
          http://localhost/api/pelanggan/pesan-sesi \
          -H "Authorization: Bearer <token>" \
          -H "Content-Type: application/json" \
          -d '{
            "mentor_id": 2,
            "pelanggan_id": 7,
            "detailKursus": "Kalkulus Dasar",
            "jadwal": "Senin, 10:00-12:00"
          }'
        ```
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mentor_id:
                  type: integer
                  example: 2
                pelanggan_id:
                  type: integer
                  example: 7
                detailKursus:
                  type: string
                  example: "Kalkulus Dasar"
                jadwal:
                  type: string
                  example: "Senin, 10:00-12:00"
              required:
                - mentor_id
                - pelanggan_id
                - detailKursus
                - jadwal
            example:
              mentor_id: 2
              pelanggan_id: 7
              detailKursus: "Kalkulus Dasar"
              jadwal: "Senin, 10:00-12:00"
      responses:
        "201":
          description: Sesi berhasil dipesan
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
              example:
                id: 10
                mentor_id: 2
                pelanggan_id: 7
                detailKursus: "Kalkulus Dasar"
                jadwal: "Senin, 10:00-12:00"
                statusSesi: "booked"
  /pelanggan/daftar-sesi:
    get:
      summary: Daftar sesi yang pernah diikuti pelanggan
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Mengambil daftar sesi yang pernah diikuti pelanggan.

        Contoh penggunaan (curl):
        ```bash
        curl -X GET \
          http://localhost/api/pelanggan/daftar-sesi \
          -H "Authorization: Bearer <token>"
        ```
      responses:
        "200":
          description: Daftar sesi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
              example:
                - id: 10
                  mentor_id: 2
                  pelanggan_id: 7
                  detailKursus: "Kalkulus Dasar"
                  jadwal: "Senin, 10:00-12:00"
                  statusSesi: "booked"
  /pelanggan/unggah-bukti/{paymentId}:
    post:
      summary: Unggah bukti pembayaran
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Unggah bukti pembayaran untuk pembayaran tertentu.

        Contoh penggunaan (curl):
        ```bash
        curl -X POST \
          http://localhost/api/pelanggan/unggah-bukti/15 \
          -H "Authorization: Bearer <token>" \
          -H "Content-Type: application/json" \
          -d '{
            "buktiPembayaran": "bukti_transfer.jpg"
          }'
        ```
      parameters:
        - in: path
          name: paymentId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                buktiPembayaran:
                  type: string
                  example: "bukti_transfer.jpg"
              required:
                - buktiPembayaran
            example:
              buktiPembayaran: "bukti_transfer.jpg"
      responses:
        "200":
          description: Bukti pembayaran berhasil diunggah
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bukti pembayaran berhasil diunggah
                  payment:
                    $ref: "#/components/schemas/Payment"
              example:
                message: Bukti pembayaran berhasil diunggah
                payment:
                  id: 15
                  user_id: 8
                  mentor_id: 2
                  session_id: 10
                  jumlah: 150000
                  statusPembayaran: "menunggu_verifikasi"
                  metodePembayaran: "transfer"
                  tanggalPembayaran: "2025-05-18T10:00:00Z"
                  buktiPembayaran: "bukti_transfer.jpg"
  /pelanggan/beri-testimoni/{sessionId}:
    post:
      summary: Beri testimoni setelah sesi selesai
      tags: [Pelanggan]
      security:
        - bearerAuth: []
      description: |
        Berikan testimoni untuk mentor setelah sesi selesai.

        Contoh penggunaan (curl):
        ```bash
        curl -X POST \
          http://localhost/api/pelanggan/beri-testimoni/10 \
          -H "Authorization: Bearer <token>" \
          -H "Content-Type: application/json" \
          -d '{
            "pelanggan_id": 7,
            "mentor_id": 2,
            "rating": 5,
            "komentar": "Mentor sangat membantu dan jelas dalam mengajar."
          }'
        ```
      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pelanggan_id:
                  type: integer
                  example: 7
                mentor_id:
                  type: integer
                  example: 2
                rating:
                  type: number
                  example: 5
                komentar:
                  type: string
                  example: "Mentor sangat membantu dan jelas dalam mengajar."
              required:
                - pelanggan_id
                - mentor_id
                - rating
                - komentar
            example:
              pelanggan_id: 7
              mentor_id: 2
              rating: 5
              komentar: "Mentor sangat membantu dan jelas dalam mengajar."
      responses:
        "201":
          description: Testimoni berhasil dibuat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Testimoni"
              example:
                id: 1
                session_id: 10
                pelanggan_id: 7
                mentor_id: 2
                rating: 5
                komentar: "Mentor sangat membantu dan jelas dalam mengajar."
                tanggal: "2025-05-18"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Pelanggan:
      type: object
      properties:
        id:
          type: integer
          example: 7
        user_id:
          type: integer
          example: 8
        user:
          type: object
          properties:
            id:
              type: integer
              example: 8
            nama:
              type: string
              example: "Siti Aminah"
            email:
              type: string
              example: "siti@example.com"
    Course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        namaCourse:
          type: string
          example: "Kalkulus Dasar"
        deskripsi:
          type: string
          example: "Materi kalkulus untuk pemula."
        mentor_id:
          type: integer
          example: 2
        mentor:
          $ref: "#/components/schemas/Mentor"
    Mentor:
      type: object
      properties:
        id:
          type: integer
          example: 2
        user_id:
          type: integer
          example: 5
        rating:
          type: number
          example: 4.8
        biayaPerSesi:
          type: number
          example: 150000
        gayaMengajar:
          type: string
          example: "Online"
        deskripsi:
          type: string
          example: "Berpengalaman mengajar matematika SMA."
        user:
          type: object
          properties:
            id:
              type: integer
              example: 5
            nama:
              type: string
              example: "Budi Santoso"
            email:
              type: string
              example: "budi@example.com"
    Session:
      type: object
      properties:
        id:
          type: integer
          example: 10
        mentor_id:
          type: integer
          example: 2
        pelanggan_id:
          type: integer
          example: 7
        detailKursus:
          type: string
          example: "Kalkulus Dasar"
        jadwal:
          type: string
          example: "Senin, 10:00-12:00"
        statusSesi:
          type: string
          description: Status sesi, hanya boleh "booked", "confirmed", atau "completed".
          example: "booked"
        mentor:
          $ref: "#/components/schemas/Mentor"
        pelanggan:
          $ref: "#/components/schemas/Pelanggan"
        testimoni:
          $ref: "#/components/schemas/Testimoni"
    Payment:
      type: object
      properties:
        id:
          type: integer
          example: 15
        user_id:
          type: integer
          example: 8
        mentor_id:
          type: integer
          example: 2
        session_id:
          type: integer
          example: 10
        jumlah:
          type: number
          example: 150000
        statusPembayaran:
          type: string
          example: "menunggu_verifikasi"
        metodePembayaran:
          type: string
          example: "transfer"
        tanggalPembayaran:
          type: string
          format: date-time
          example: "2025-05-18T10:00:00Z"
        buktiPembayaran:
          type: string
          example: "bukti_transfer.jpg"
    Testimoni:
      type: object
      properties:
        id:
          type: integer
          example: 1
        session_id:
          type: integer
          example: 10
        pelanggan_id:
          type: integer
          example: 7
        mentor_id:
          type: integer
          example: 2
        rating:
          type: number
          example: 5
        komentar:
          type: string
          example: "Mentor sangat membantu dan jelas dalam mengajar."
        tanggal:
          type: string
          format: date
          example: "2025-05-18"
